name: nestjs-starter

services:
  db:
    image: postgres:18.1
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_starter
    ports:
      - '5432:5432'
